// <auto-generated />
using System;
using GhcSamplePs.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GhcSamplePs.Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251202032639_AddPlayerStatisticsTable")]
    partial class AddPlayerStatisticsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GhcSamplePs.Core.Models.PlayerManagement.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DateOfBirth")
                        .HasDatabaseName("IX_Players_DateOfBirth");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Players_Name");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Players_UserId");

                    b.HasIndex("UserId", "Name")
                        .HasDatabaseName("IX_Players_UserId_Name");

                    b.ToTable("Players", (string)null);
                });

            modelBuilder.Entity("GhcSamplePs.Core.Models.PlayerManagement.PlayerStatistic", b =>
                {
                    b.Property<int>("PlayerStatisticId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerStatisticId"));

                    b.Property<int>("Assists")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("GameDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Goals")
                        .HasColumnType("int");

                    b.Property<bool>("IsStarter")
                        .HasColumnType("bit");

                    b.Property<int>("JerseyNumber")
                        .HasColumnType("int");

                    b.Property<int>("MinutesPlayed")
                        .HasColumnType("int");

                    b.Property<int>("TeamPlayerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PlayerStatisticId");

                    b.HasIndex("GameDate")
                        .HasDatabaseName("IX_PlayerStatistics_GameDate");

                    b.HasIndex("TeamPlayerId")
                        .HasDatabaseName("IX_PlayerStatistics_TeamPlayerId");

                    b.HasIndex("TeamPlayerId", "GameDate")
                        .HasDatabaseName("IX_PlayerStatistics_TeamPlayerId_GameDate");

                    b.ToTable("PlayerStatistics", (string)null);
                });

            modelBuilder.Entity("GhcSamplePs.Core.Models.PlayerManagement.TeamPlayer", b =>
                {
                    b.Property<int>("TeamPlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamPlayerId"));

                    b.Property<string>("ChampionshipName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("JoinedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LeftDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TeamPlayerId");

                    b.HasIndex("LeftDate")
                        .HasDatabaseName("IX_TeamPlayers_IsActive");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("IX_TeamPlayers_PlayerId");

                    b.HasIndex("TeamName")
                        .HasDatabaseName("IX_TeamPlayers_TeamName");

                    b.HasIndex("PlayerId", "LeftDate")
                        .HasDatabaseName("IX_TeamPlayers_PlayerId_IsActive");

                    b.HasIndex("PlayerId", "TeamName", "ChampionshipName")
                        .HasDatabaseName("IX_TeamPlayers_PlayerId_TeamName_ChampionshipName");

                    b.ToTable("TeamPlayers", (string)null);
                });

            modelBuilder.Entity("GhcSamplePs.Core.Models.PlayerManagement.PlayerStatistic", b =>
                {
                    b.HasOne("GhcSamplePs.Core.Models.PlayerManagement.TeamPlayer", "TeamPlayer")
                        .WithMany()
                        .HasForeignKey("TeamPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamPlayer");
                });

            modelBuilder.Entity("GhcSamplePs.Core.Models.PlayerManagement.TeamPlayer", b =>
                {
                    b.HasOne("GhcSamplePs.Core.Models.PlayerManagement.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });
#pragma warning restore 612, 618
        }
    }
}
